'\" t
.\"     Title: dvd_backup
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/26/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DVD_BACKUP" "1" "09/26/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dvd_backup \- backup an entire DVD or a Video Title Set
.SH "SYNOPSIS"
.sp
\fBdvd_backup\fR [\fIPATH\fR] [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The dvd_backup(1) program will copy either an entire DVD\(cqs contents or a video title set to the filesystem\&. The output directory will be the UDF volume name of the disc\&.
.sp
The default device is based on your operating system, and is the primary optical drive\&.
.sp
For backing up a single track, see dvd_copy(1)\&.
.SH "OPTIONS"
.PP
\fB\-i, \-\-ifos\fR
.RS 4
Back up the IFO and BUP files\&.
.RE
.PP
\fB\-T, \-\-vts\fR=\fIVTS\fR
.RS 4
Back up a video title set number\&.
.RE
.sp
\fB\-h, \-\-help\fR Display help output\&.
.SH "SEE ALSO"
.sp
dvd_copy(1), dvd_info(1)
.SH "BUGS"
.sp
\fBdvd_backup\fR does not wait for an optical device to be ready\&. Wait for it to finish "polling" before running the program\&.
.sp
Please file bugs at https://github\&.com/beandog/dvd_info/issues
.SH "AUTHOR"
.sp
dvd_copy was written by Steve Dibb <steve\&.dibb@gmail\&.com>
.SH "RESOURCES"
.sp
Source code available at GitHub: https://github\&.com/beandog/dvd_info
.sp
Main web site: http://dvds\&.beandog\&.org
.SH "COPYING"
.sp
Copyright (C) 2019 Steve Dibb\&. Free use of this software is granted under the terms of the GNU General Public License, version 2 (GPL)\&.
