'\" t
.\"     Title: dvd_info
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/08/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DVD_INFO" "1" "06/08/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dvd_info \- displays information about a DVD
.SH "SYNOPSIS"
.sp
\fBdvd_info\fR [\fIPATH\fR] [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The dvd_info(1) program displays information about a DVD optical disc, image, or directory in human\-readable, JSON, or formatted chapter outputs\&.
.sp
The default device is based on your operating system, and is the primary optical drive\&.
.sp
DVDs can store two kinds of subtitles \(em VOBSUB, which are images, and closed captioning, which are text\&. Only the VOBSUB subtitles are reported here\&. Getting access to the closed captioning ones would require demuxing the stream\&.
.sp
Some tracks are marked as \fIinvalid\fR\&. These are cases where it may have garbage data intentionally authored onto the disc to break applications\&. dvd_info does some checks on each track to look for properties that would flag it as invalid\&. These can be skipped in listing tracks by using the \fI\-\-quiet\fR option\&.
.sp
DVDs may also have audio and subtitle streams marked as inactive as well\&.
.SH "OPTIONS"
.PP
\fB\-t, \-\-track\fR=\fITRACK\fR
.RS 4
Limit output to the selected track\&. By default, list all tracks\&.
.RE
.PP
\fB\-j, \-\-json\fR
.RS 4
Format output in JSON\&. All detailed information is included\&.
.RE
.PP
\fB\-v, \-\-video\fR
.RS 4
Display detailed information about video streams\&.
.RE
.PP
\fB\-a, \-\-audio\fR
.RS 4
Display detailed information about audio streams\&.
.RE
.PP
\fB\-s, \-\-subtitles\fR
.RS 4
Display detailed information about VOBSUB subtitles\&.
.RE
.PP
\fB\-c, \-\-chapters\fR
.RS 4
Display detailed information about chapters\&.
.RE
.PP
\fB\-x, \-\-all\fR
.RS 4
Display all optional detailed information\&.
.RE
.PP
\fB\-A, \-\-has\-audio\fR
.RS 4
Limit output to tracks that have audio tracks\&.
.RE
.PP
\fB\-S, \-\-has\-subtracks\fR
.RS 4
Limit output to tracks that have subtracks\&.
.RE
.PP
\fB\-E, \-\-seconds\fR=\fISECONDS\fR
.RS 4
Limit output to tracks with a minimum length of number of seconds\&.
.RE
.PP
\fB\-M, \-\-minutes\fR=\fIMINUTES\fR
.RS 4
Limit output to tracks with a minimum length of number of minutes\&. Cannot be used in combination with
\fI\-\-seconds\fR\&.
.RE
.PP
\fB\-T, \-\-vts\fR=\fINUMBER\fR
.RS 4
Limit output to tracks in Video Title Set number\&. Enables verbose\&.
.RE
.PP
\fB\-g, \-\-xchap\fR
.RS 4
Display track chapters in export format suitable for mkvmerge(1) and ogmmerge(1)\&.
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Don\(cqt display disc title header, invalid tracks, tracks with duration less than one second, and inactive streams\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Display help output\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Display version information\&.
.RE
.SH "SEE ALSO"
.sp
dvd_copy(1)
.SH "BUGS"
.sp
Please file bugs at https://github\&.com/beandog/dvd_info/issues
.SH "AUTHOR"
.sp
dvd_info was written by Steve Dibb <steve\&.dibb@gmail\&.com> and was originally a clone of lsdvd(1)\&.
.SH "RESOURCES"
.sp
Source code available at GitHub: https://github\&.com/beandog/dvd_info
.sp
Main web site: https://dvds\&.beandog\&.org
.SH "COPYING"
.sp
Copyright (C) 2019 Steve Dibb\&. Free use of this software is granted under the terms of the GNU General Public License, version 2 (GPL)\&.
