'\" t
.\"     Title: dvd_backup
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2024-10-31
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DVD_BACKUP" "1" "2024-10-31" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dvd_backup \- backup an entire DVD or a Video Title Set
.SH "SYNOPSIS"
.sp
\fBdvd_backup\fP [\fIPATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
The dvd_backup(1) program will copy either an entire DVD\(cqs contents or a video
title set to the filesystem. The output directory will be the UDF volume name
of the disc, the name passed for the directory, or DVD_VIDEO if no label
exists.
.sp
dvd_backup will read each block individually, and write it to the output
file(s). If a block cannot be read, it will skip it, which should preserve
playback though it will skip where data is missed.
.sp
If a disc is damaged, reading can take a long time for each broken block.
The amount of skipped blocks is displayed on output.
.sp
The default device is based on your operating system, and is the primary
optical drive.
.sp
For backing up a single track, see dvd_copy(1).
.SH "OPTIONS"
.sp
\fB\-n, \-\-name\fP
.RS 4
Set DVD name to backup directory to.
.RE
.sp
\fB\-i, \-\-ifos\fP
.RS 4
Back up the IFO and BUP files.
.RE
.sp
\fB\-T, \-\-vts\fP=\fIVTS\fP
.RS 4
Back up a video title set number.
.RE
.sp
\fB\-h, \-\-help\fP
Display help output.
.SH "SEE ALSO"
.sp
dvd_copy(1), dvd_drive_status(1), dvd_info(1), dvd_player(1), dvd_rip(1)
.SH "BUGS"
.sp
\fBdvd_backup\fP does not wait for an optical device to be ready. Wait for it to
finish "polling" before running the program.
.sp
Please file bugs at \c
.URL "https://github.com/beandog/dvd_info/issues" "" ""
.SH "AUTHOR"
.sp
dvd_copy was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/dvd_info" "" ""
.SH "COPYING"
.sp
Copyright (C) 2023 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).