'\" t
.\"     Title: dvd_copy
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-12-26
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DVD_COPY" "1" "2023-12-26" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dvd_copy \- copy a track from a DVD to a file or stdout
.SH "SYNOPSIS"
.sp
\fBdvd_copy\fP [\fIPATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
The dvd_copy(1) program will copy a track from a DVD optical disc, image,
or directory to either a file or stdout.
.sp
The default device is based on your operating system, and is the primary
optical drive.
.sp
Default output filename is \fIdvd_track_#.mpg\fP where the number is
a zero\-padded string of the longest track.
.sp
Some DVDs are intentionally authored to break playback and copying software
like this one. An example of a "poisoned" DVD is where the indexes on the disc
point to the same locations multiple times, and your rip may end up to be
dozens of gigabytes in size.
.sp
dvd_info(1) examines tracks closely to check for flags that would make a track
invalid, and you can use that as a reference if something may be broken or
not. \fIdvd_copy\fP doesn\(cqt use any checks, and will copy whatever is requested.
.sp
Sending the track directly to stdout makes it useful for things like piping to
other programs. Since the output is decrypted, it\(cqs a clean stream that at
that point can be re\-encoded, remuxed, etc.
.sp
An example using ffmpeg, remuxing a track into a Matroska file:
.sp
$ dvd_copy \-o \- | ffmpeg \-fflags +genpts \-i \- \-c copy dvd_track.mkv
.sp
To backup an entire DVD, see dvd_backup(1).
.SH "OPTIONS"
.sp
\fB\-t, \-\-track\fP=\fITITLE\fP
.RS 4
Copy the selected track number. Default is the longest track.
.RE
.sp
\fB\-c, \-\-chapter\fP=\fICHAPTER[\-[CHAPTER]]\fP
Copy the selected chapter range. Default is to copy all chapters.
.sp
\fB\-o, \-\-output\fP=\fIFILENAME\fP
Save to filename. Default is \fIdvd_track_.mpg\fP where  is the
zero\-padded track number.
.sp
.if n .RS 4
.nf
.fam C
\*(AqFILENAME\*(Aq can be \*(Aq\-\*(Aq to send to standard output. All display output
is switched to standard error output.
.fam
.fi
.if n .RE
.sp
\fB\-h, \-\-help\fP
Display help output.
.sp
\fB\-\-version\fP
Display version information.
.SH "SEE ALSO"
.sp
dvd_info(1), dvd_backup(1)
.SH "BUGS"
.sp
\fBdvd_copy\fP does not wait for an optical device to be ready. Wait for it to
finish "polling" before running the program.
.sp
Please file bugs at \c
.URL "https://github.com/beandog/dvd_info/issues" "" ""
.SH "AUTHOR"
.sp
dvd_copy was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/dvd_info" "" ""
.SH "COPYING"
.sp
Copyright (C) 2023 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).