'\" t
.\"     Title: dvd_info
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-12-22
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DVD_INFO" "1" "2023-12-22" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
dvd_info \- displays information about a DVD
.SH "SYNOPSIS"
.sp
\fBdvd_info\fP [\fIDVD PATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
Displays information about a DVD optical disc, image, or directory in
human\-readable, JSON, or formatted chapter outputs.
.sp
The default device is based on your operating system, and is the primary
optical drive.
.sp
DVDs can store two kinds of subtitles \(em VOBSUB, which are images, and closed
captioning, which are text. Only the VOBSUB subtitles are reported here.
.sp
DVDs may be authored by the provider to intentionally have bugs on the
structure that will cause problems during playback or ripping if the correct
track is not selected. \fBdvd_info\fP does its best to work around and flag these
tracks as invalid. See the JSON or verbose output formats to see which ones
are tagged.
.sp
DVDs may also have audio and subtitle streams marked as inactive as well. This
is normal, and usually won\(cqt show up at all in other DVD applications.
.sp
The ID of a DVD is a md5 hash of the IFOs on the disc.
.sp
The disc title is the volume name of the DVD\(cqs UDF. It will only appear if the
source is an ISO file or a physical disc.
.sp
DVDs support three audio codecs: ac3 (Dolby Digital), dts, and pcm. Dolby
Digital and DTS support up to 6 channels (5.1 surround sound). PCM supports
stereo only.
.sp
DVDs support multiple audio and subtitle languages. These are displayed in
output as a two letter string. Examples: de \- German, en \- English, fr \-
French, it \- Italian, etc.
.SH "OPTIONS"
.sp
\fB\-t, \-\-track\fP=\fITRACK\fP
.RS 4
Limit output to the selected track. By default, list all tracks.
.RE
.sp
\fB\-j, \-\-json\fP
.RS 4
Format output in JSON. All detailed information is included.
.RE
.sp
\fB\-v, \-\-video\fP
.RS 4
Display detailed information about video streams.
.RE
.sp
\fB\-a, \-\-audio\fP
.RS 4
Display detailed information about audio streams.
.RE
.sp
\fB\-s, \-\-subtitles\fP
.RS 4
Display detailed information about VOBSUB subtitles.
.RE
.sp
\fB\-c, \-\-chapters\fP
.RS 4
Display detailed information about chapters.
.RE
.sp
\fB\-d, \-\-cells\fP
.RS 4
Display detailed information about cells.
.RE
.sp
\fB\-x, \-\-all\fP
.RS 4
Display all optional detailed information.
.RE
.sp
\fB\-l, \-\-longest\fP
.RS 4
Only display the longest track.
.RE
.sp
\fB\-A, \-\-has\-audio\fP
.RS 4
Limit output to tracks that have audio streams.
.RE
.sp
\fB\-S, \-\-has\-subtitles\fP
.RS 4
Limit output to tracks that have VOBSUB subtitles.
.RE
.sp
\fB\-E, \-\-seconds\fP=\fISECONDS\fP
.RS 4
Limit output to tracks with a minimum length of number of seconds.
.RE
.sp
\fB\-M, \-\-minutes\fP=\fIMINUTES\fP
.RS 4
Limit output to tracks with a minimum length of number of minutes.
Cannot be used in combination with \fI\-\-seconds\fP.
.RE
.sp
\fB\-T, \-\-vts\fP=\fINUMBER\fP
.RS 4
Limit output to tracks in Video Title Set number.
.RE
.sp
*\-L, \-\-valid
.RS 4
Don\(cqt display tracks that may be flagged as broken or invalid.
.RE
.sp
\fB\-i, \-\-id\fP
.RS 4
Display DVD unique identifier only.
.RE
.sp
\fB\-u, \-\-volume\fP
.RS 4
Display DVD UDF volume name only.
.RE
.sp
\fB\-g, \-\-xchap\fP
.RS 4
Display track chapters in export format suitable for mkvmerge(1).
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Display help output.
.RE
.sp
\fB\-\-version\fP
.RS 4
Display version information.
.RE
.SH "SEE ALSO"
.sp
dvd_backup(1), dvd_copy(1), dvd_drive_status(1), dvd_player(1), dvd_rip(1)
.SH "BUGS"
.sp
Please file bugs at \c
.URL "https://github.com/beandog/dvd_info/issues" "" ""
.SH "AUTHOR"
.sp
dvd_info was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
and was started as a
clone of lsdvd(1).
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/dvd_info" "" ""
.sp
Main web site: \c
.URL "https://dvds.beandog.org" "" ""
.SH "COPYING"
.sp
Copyright (C) 2020 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).