.\" Manpage for dvd_info
.\" Contact steve.dibb@gmail.com to correct errors or typos.
.TH dvd_info 1 "04 August 2018" "1.3" "dvd_info man page"
.SH NAME
dvd_info \- display information about a DVD
.SH SYNOPSIS
\fBdvd_info\fR [options] [\-t track number] [dvd path]
.SH DESCRIPTION
\fBdvd_info\fR displays information about a DVD including its tracks, playback length, audio tracks, codecs, languages, subtitles, and chapters.

Output formats are human-readable text, JSON, OGM chapter format, DVD id or title.

DVD path can be a device name, a single file, or a directory. Default is optical drive.
.SH OPTIONS
.TP
\fB-t, --track # \fR
Limit to one track number (default: longest).
.TP
\fB-v, --video \fR
Display video format, aspect ratio, height and width dimensions, frames per second, and display format. 
.TP
\fB-a, --audio \fR
Display audio stream indexes, languages, codecs, number of channels, stream ids, and active statuses.
.TP
\fB-s, --subtitles \fR
Display VobSub subtitle indexes, languages, stream ids, and active statuses.
.TP
\fB-c, --chapters \fR
Display chapter indexes, time durations.
.TP
\fB-d, --cells \fR
Display cell indexes, time duration, first and last filesystem sectors.
.TP
\fB-x, --all \fR
Display all information.
.TP
\fB-q, --quiet \fR
Don't display DVD title, longest track, invalid tracks, and inactive streams.

.SH FORMATTING
.TP
\fB-j, --json \fR
Display all information in JSON output.
.TP
\fB-o, --ogm \fR
Display OGM chapter format for specified track (default: longest).
.TP
\fB-i, --id \fR
Display DVD id only (from libdvdread).
.TP
\fB-T, --title \fR
Display UDF volume name only (dvd path must be a device or a file).

.SH QUIET MODE, INVALID TRACKS, AND INACTIVE STREAMS
.TP
There are a few ways a track can be marked as invalid - the filesystem is inaccessible, the VTS or IFO is bad, the track has an empty length, or the description of sector layouts is incorrect. There could be accidental errors when the disc was authored, or it was by design in order to break DVD software. The disc could be physically damaged as well. Invalid DVD tracks appear as completely empty in dvd_info's output. With quiet mode enabled, it will not be listed at all.
.TP
A DVD can have a an audio or subtitle stream marked as "inactive". The title track information will display the sum of active audio tracks, and the detailed information will list both active and inactive. Enabling quiet mode supresses inactive streams from being displayed.
.TP
In both cases, the JSON output format has variables for valid and inactive attributes.

.SH HISTORY
dvd_info closely mirrors the human-readable output of lsdvd.

.SH SEE ALSO
dvd_copy(1), dvd_drive_status(1), dvd_eject(1)

.SH AUTHOR
Steve Dibb (steve.dibb@gmail.com) http://dvds.beandog.org
